## .github/workflows/micropip-installable.yml
#name: PYODIDE
#
#on:
#  push:
#
#jobs:
#  # Build for pyodide 0.27
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#
#    - uses: actions/setup-python@v5
#      with:
#        python-version: 3.12 # same as the version in Pyodide
#
#    - uses: mymindstorm/setup-emsdk@v14
#      with:
#        version: 3.1.58
#
#    - run: pip install pyodide-build>=0.27.0
#
#    - run: pyodide build
#
#    - uses: actions/upload-artifact@v4
#      with:
#        name: pyodide_wheel
#        path: dist
#
#  # this is the job which you add to run pyodide-test
#  test:
#    needs: build
#    uses: pyodide/pytest-pyodide/.github/workflows/main.yaml@main
#    with:
#      build-artifact-name: pyodide_wheel
#      build-artifact-path: dist
#      browser: firefox
#      runner: selenium
#      pyodide-version: 0.27.2
