# Workflow: Documentation Book
# Purpose: This workflow generates comprehensive documentation for the project, including
#          API documentation, test coverage reports, and processed Jupyter notebooks.
#          It then combines these into a documentation book and publishes it.
name: "book"

# Trigger: This workflow runs on every push to the repository
on:
  push:
    branches:
      - main

# Permissions: Write access to checks for test reports and read access to repository contents
permissions:
    checks: write
    contents: read

jobs:
  # Job: pdoc
  # Purpose: Generates API documentation using pdoc
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      # Step: Set up the virtual environment
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.71

      - name: Export notebook via wasm
        run: |
          uv pip install --no-cache-dir marimo
          mkdir -p artifacts/notebooks
          # export as readonly, with code locked
          uv run marimo export html-wasm book/marimo/demo.py -o artifacts/marimo/demo/index.html --mode edit

      - name: Upload documentation
        #if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1


  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      # Step: Set up the virtual environment
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.71

      # Step: Generate API documentation with pdoc
      # Creates documentation from the source code in src/jquantstats
      - uses: tschm/cradle/actions/pdoc@v0.1.71
        with:
          source-folder: src/jquantstats

  # Job: test
  # Purpose: Runs tests and generates coverage reports
  test:
    runs-on: "ubuntu-latest"
    steps:
      # Step: Set up the virtual environment
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.71

      # Step: Run tests and generate coverage reports
      # Also uploads coverage data to Coveralls if enabled
      - uses: tschm/cradle/actions/coverage@main
        with:
          tests-folder: src/tests
          source-folder: src/jquantstats
          coveralls: 'true'

  # Job: jupyter
  # Purpose: Processes Jupyter notebooks for inclusion in documentation
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      # Step: Set up the virtual environment
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.71

      # Step: Process Jupyter notebooks
      # Executes and prepares notebooks for documentation
      - uses: tschm/cradle/actions/jupyter@v0.1.71

  # Job: book
  # Purpose: Combines and publishes the documentation
  book:
    runs-on: "ubuntu-latest"
    # This job depends on the completion of test, pdoc, and jupyter jobs
    needs: [test, pdoc, jupyter, marimo]

    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # Step: Upload the generated documentation book
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.71
