# Workflow: Deptry
# Purpose: This workflow identifies missing and obsolete dependencies in the project.
#          It helps maintain a clean dependency tree by detecting unused packages and
#          implicit dependencies that should be explicitly declared.
name: "Deptry"

# Trigger: This workflow runs on every push and on pull requests to the main branch
on:
  push:
  pull_request:
    # Only run on pull requests targeting the main branch
    branches: [ main ]

# Permissions: Only read access to repository contents is needed
permissions:
    contents: read

jobs:
  # Job: Dependencies
  # Purpose: Checks the project's dependency health using deptry
  Dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Run deptry
        uses: tschm/cradle/actions/deptry@v0.2.1
        with:
          source-folder: src/jquantstats
