name: pyodide

on:
  push:

permissions:
  contents: read

jobs:
  test-pyodide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Start HTTP server in background
        run: |
          python -m http.server 8000 &
          echo $! > server_pid.txt
          sleep 2

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Puppeteer test to load pyodide & install wheel
        shell: bash
        run: |
          node --input-type=module <<'EOF'
          import puppeteer from "puppeteer";

          (async () => {
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });

            const page = await browser.newPage();

            await page.goto('about:blank');

            page.on('console', msg => console.log('PAGE LOG:', msg.text()));

            await page.evaluate(async () => {
              // Inject Pyodide script
              const script = document.createElement("script");
              script.src = "https://cdn.jsdelivr.net/pyodide/v0.25.1/full/pyodide.js";
              document.head.appendChild(script);
              await new Promise((resolve) => {
                script.onload = resolve;
              });

              const pyodide = await loadPyodide({
                indexURL: "https://cdn.jsdelivr.net/pyodide/v0.25.1/full/"
              });

              console.log("✅ Pyodide loaded");

              await pyodide.loadPackage("micropip");

              const wheelUrl = "http://127.0.0.1:8000/jquantstats-0.1.0-py3-none-any.whl";

              console.log(`Installing wheel from: ${wheelUrl}`);

              await pyodide.runPythonAsync(`
                import micropip
                await micropip.install("${wheelUrl}")
                import jquantstats
                print("✅ jquantstats imported successfully")
              `);
            });

            await browser.close();
          })();
          EOF

      - name: Stop HTTP server
        run: kill $(cat server_pid.txt) || true
