name: WASM2

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python with uv
        run: |
          uv venv .venv
          echo ".venv/bin" >> $GITHUB_PATH

      - name: Build wheel with uv
        run: |
          uv pip install hatch
          hatch build
          #uv pip install -e .  # Install package dependencies
          #python -m build --wheel --no-isolation
          echo "Built wheel:"
          ls -la dist/

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-wheel
          path: dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: tschm/cradle/actions/pyodide@main
        with:
          build-artifact-name: wasm-wheel
          build-artifact-path: dist
          browser: firefox
          runner: selenium
          pyodide-version: 0.27.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
