name: WASM2

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          pip install build pytest-cov

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-wheel
          path: dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: tschm/cradle/actions/pyodide@main
        with:
          build-artifact-name: wasm-wheel
          build-artifact-path: dist
          browser: firefox
          runner: selenium
          pyodide-version: 0.27.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
